title:              "Markethon Project"
tagline:            "Study Must Go On"
email:              "deepdiver@kakao.com"
description:        "장거리 성장을 위한 한걸음"
author:             "Markethoner"
baseurl:            "/"
url:                "https://markethon.space"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.jpg"

# Social Profiles
instagram_username: instagram_markethoner

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
# 블로그 disqus shortname
disqus:
  shortname: markethoner
