title:              "Markethon Project"
tagline:            "Study Must Go On"
email:              "deepdiver@kakao.com"
description:        "블로그 설명"
author:             "Markethoner"
baseurl:            "/"
url:                "https://markethon.space"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.jpg"

# Social Profiles
instagram_username: instagram_markethon_project

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
